name: Attention Comment
on:
  pull_request:
    branches:
      - master
    paths:
      - ".api-version"

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '今回のデプロイで生じた変更をWikiに更新しましたか？'
            })
